/**
 * PDF certificate generator for Verifiable Credentials.
 *
 * Generates PDF certificates that embed the VC using pdfkit.
 * Works completely offline -- no network requests or font downloads.
 *
 * The PDF includes:
 *  - Certificate header with credential type
 *  - Issuer and subject information
 *  - Validity dates
 *  - The full VC JSON-LD (for machine-readability)
 */

import PDFDocument from "pdfkit";
import type { VerifiableCredential } from "@opencred/vc-core";

/**
 * Generate a PDF certificate from a VerifiableCredential.
 *
 * @param credential - The signed VerifiableCredential.
 * @returns A Buffer containing the PDF document.
 */
export async function generatePdf(credential: VerifiableCredential): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        info: {
          Title: "Verifiable Credential Certificate",
          Author: "OpenCred Desktop",
          Subject: `Credential: ${credential.id}`,
        },
      });

      const buffers: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      // Header
      doc.fontSize(24).text("Verifiable Credential", { align: "center" });
      doc.moveDown(0.5);

      // Credential types
      const types = Array.isArray(credential.type)
        ? credential.type.join(", ")
        : String(credential.type);
      doc.fontSize(14).fillColor("#444444").text(types, { align: "center" });
      doc.moveDown(1);

      // Horizontal rule
      doc.strokeColor("#cccccc").lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(1);

      // Credential ID
      doc.fontSize(10).fillColor("#666666").text("Credential ID:", { continued: true });
      doc.fillColor("#000000").text(` ${credential.id}`);
      doc.moveDown(0.5);

      // Issuer
      const issuerDisplay =
        typeof credential.issuer === "string" ? credential.issuer : credential.issuer.id;
      doc.fontSize(10).fillColor("#666666").text("Issuer:", { continued: true });
      doc.fillColor("#000000").text(` ${issuerDisplay}`);
      doc.moveDown(0.5);

      // Validity
      doc.fontSize(10).fillColor("#666666").text("Valid From:", { continued: true });
      doc.fillColor("#000000").text(` ${credential.validFrom}`);
      if (credential.validUntil) {
        doc.fontSize(10).fillColor("#666666").text("Valid Until:", { continued: true });
        doc.fillColor("#000000").text(` ${credential.validUntil}`);
      }
      doc.moveDown(0.5);

      // Subject
      const subject = credential.credentialSubject;
      doc.fontSize(10).fillColor("#666666").text("Subject:");
      doc.moveDown(0.3);
      for (const [key, value] of Object.entries(subject)) {
        if (key === "id") {
          doc.fontSize(10).fillColor("#666666").text("  Subject ID:", { continued: true });
          doc.fillColor("#000000").text(` ${String(value)}`);
        } else {
          doc.fontSize(10).fillColor("#666666").text(`  ${key}:`, { continued: true });
          doc.fillColor("#000000").text(` ${String(value)}`);
        }
      }
      doc.moveDown(1);

      // Proof info
      doc.strokeColor("#cccccc").lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);

      doc.fontSize(10).fillColor("#666666").text("Digital Signature");
      doc.moveDown(0.3);
      doc.fontSize(8).fillColor("#444444").text(`Type: ${credential.proof.type}`);
      if (credential.proof.cryptosuite) {
        doc.text(`Cryptosuite: ${credential.proof.cryptosuite}`);
      }
      doc.text(`Created: ${credential.proof.created}`);
      doc.text(`Verification Method: ${credential.proof.verificationMethod}`);
      doc.moveDown(1);

      // Embedded JSON-LD
      doc.strokeColor("#cccccc").lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);

      doc.fontSize(8).fillColor("#666666").text("Machine-Readable Credential (JSON-LD):");
      doc.moveDown(0.3);
      doc
        .fontSize(6)
        .fillColor("#333333")
        .font("Courier")
        .text(JSON.stringify(credential, null, 2), {
          width: 495,
        });

      // Footer
      doc.moveDown(1);
      doc
        .font("Helvetica")
        .fontSize(7)
        .fillColor("#999999")
        .text(
          "This document was generated by OpenCred Desktop. Verify the credential using the embedded JSON-LD data.",
          { align: "center" },
        );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
