/**
 * embed-svgs.cjs — Read SVG template files and generate a TypeScript module
 * with their contents as string constants.
 *
 * This eliminates runtime fs.readFileSync calls, making the package
 * compatible with bundlers (esbuild, webpack, rollup) that can't
 * statically resolve dynamic file reads.
 *
 * Runs as part of the build step, before tsc.
 */

const fs = require("fs");
const path = require("path");

const templatesDir = path.resolve(__dirname, "..", "src", "templates");
const outFile = path.resolve(__dirname, "..", "src", "svg-data.ts");

const svgFiles = fs.readdirSync(templatesDir).filter((f) => f.endsWith(".svg")).sort();

if (svgFiles.length === 0) {
  console.error("[embed-svgs] No SVG files found in", templatesDir);
  process.exit(1);
}

const lines = [
  "// Auto-generated by scripts/embed-svgs.cjs — do not edit manually.",
  "// Edit the SVG files in src/templates/ and run the build.",
  "",
];

for (const file of svgFiles) {
  const content = fs.readFileSync(path.join(templatesDir, file), "utf-8");
  // Convert filename to camelCase constant name: "education.svg" → "educationSvg"
  const name = file.replace(".svg", "").replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "Svg";
  // Use a tagged template to preserve the SVG content exactly
  lines.push(`export const ${name} = ${JSON.stringify(content)};`);
  lines.push("");
}

fs.writeFileSync(outFile, lines.join("\n"));
console.log(`[embed-svgs] Generated ${outFile} with ${svgFiles.length} templates`);
