/**
 * embed-fonts.cjs — read the bundled .ttf brand fonts and emit a TypeScript
 * module with their contents as base64 string constants.
 *
 * PDFKit needs a Buffer/path to embed a font, and the generator is shipped
 * to bundlers (esbuild on desktop + server) that can't statically resolve
 * runtime fs reads. Embedding the fonts as base64 makes the package fully
 * self-contained — the same reason packages/templates embeds its SVGs.
 *
 * Runs as part of the build, before tsc. Output is committed and
 * prettier-ignored.
 */

const fs = require("fs");
const path = require("path");

const fontsDir = path.resolve(__dirname, "..", "src", "fonts");
const outFile = path.resolve(__dirname, "..", "src", "font-data.ts");

const fontFiles = fs
  .readdirSync(fontsDir)
  .filter((f) => /\.(ttf|otf)$/i.test(f))
  .sort();

if (fontFiles.length === 0) {
  console.error("[embed-fonts] No .ttf/.otf files found in", fontsDir);
  process.exit(1);
}

const lines = [
  "// Auto-generated by scripts/embed-fonts.cjs — do not edit manually.",
  "// Add/replace .ttf files in src/fonts/ and run the build.",
  "",
];

for (const file of fontFiles) {
  const base64 = fs.readFileSync(path.join(fontsDir, file)).toString("base64");
  // "Geist-SemiBold.ttf" -> "GeistSemiBold"
  const name = file.replace(/\.(ttf|otf)$/i, "").replace(/[-_]([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
  lines.push(`export const ${name} = "${base64}";`);
  lines.push("");
}

fs.writeFileSync(outFile, lines.join("\n"));
console.log(`[embed-fonts] Generated ${outFile} with ${fontFiles.length} fonts`);
