// AUTO-GENERATED by scripts/fetch-and-embed-schemas.mjs — do not edit by hand.
// Regenerate via `pnpm --filter @opencred/schema-engine build`.

import { SchemaRegistry } from "./schema-registry.js";
import type { SchemaDefinition } from "./types.js";
import {
  electricityV1,
  salarySlipV1,
  immunizationV1,
  prescriptionV1,
  testResultV1,
  insurancePolicyV1,
  functionalIdentityV1,
  employmentOfferLetterV1,
  businessEntityV1,
  openBadgesV3,
  difVerifiedPersonV1,
  difProofOfAgeV1,
  traceabilityCommercialInvoiceV1,
  traceabilityBillOfLadingV1,
  traceabilityHouseBillOfLadingV1,
  traceabilityUsmcaCertificationOfOriginV1,
  traceabilityCertificationOfOriginV1,
  traceabilityPurchaseOrderV1,
  traceabilityOrderConfirmationV1,
  traceabilityPackingListV1,
  traceabilityIataAirWaybillV1,
  traceabilityImporterSecurityFilingV1,
  traceabilityMillTestReportV1,
  traceabilitySbomV1,
  traceabilityGapInspectionV1,
  traceabilityFoodGradeInspectionV1,
  traceabilityPhytosanitaryV1,
  traceabilityOilAndGasProductV1,
  traceabilityNaturalGasEnvironmentalPassportV1,
  traceabilitySimaSteelImportLicenseV1,
  traceabilityShippingInstructionsV1,
  traceabilityFreightManifestV1,
  traceabilityDeliveryScheduleV1,
} from "./schema-data.js";

export function createBuiltInRegistry(): SchemaRegistry {
  const registry = new SchemaRegistry();
  registry.register({
    id: "electricity/v1",
    schema: electricityV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/electricity/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "366f042d00f8853dfa2c449ef9d820b0de8276ec719b2c3d4185f88410219b4e",
    source: {"kind":"defined","upstreamUrl":"https://schema.beckn.io/ElectricityCredential/1.0/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "salary-slip/v1",
    schema: salarySlipV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "fb113aa7a2e49fa9abd5c87abfab30c89369ff12d2d8b0bf9857669a1b735fea",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/salary-slip/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "immunization/v1",
    schema: immunizationV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/immunization/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "e88bb7c284020861325054e79a3ede3078eed8df8a2b413e0ee2508ed0356757",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/immunization/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "prescription/v1",
    schema: prescriptionV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/prescription/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "43bc583f19f1f236cf3009e221791355a80583f02b0b28d0a3e17c68e6af1a97",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/prescription/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "test-result/v1",
    schema: testResultV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/test-result/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "55f9caf38bf34608bd6fb6f4d7cbbeb996e91388050df4587be8b7a5a6174f8a",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/test-result/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "insurance-policy/v1",
    schema: insurancePolicyV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/insurance-policy/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "c30e6708a5de6d9ea05e4ae0a293769269ccb208a21d68e43252674f6c7f6905",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/insurance-policy/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "functional-identity/v1",
    schema: functionalIdentityV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/functional-identity/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "bf442dc05eacd32153138aa2f9bb924c1a5a7cbaa00f8b716defa0222bd7c234",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/functional-identity/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "employment-offer-letter/v1",
    schema: employmentOfferLetterV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/employment-offer-letter/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "3b7d754b056a67f964d3554ca675b5b31b881c3d2f04680876fd3bef46cb48b1",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/employment-offer-letter/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "business-entity/v1",
    schema: businessEntityV1,
    contextUrl: "https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/business-entity/v1/context.jsonld",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "879ac9707361edfd5d47d6fdd7712576d2602dd2a54a755ff596fd12e6395879",
    source: {"kind":"defined","upstreamUrl":"https://raw.githubusercontent.com/nfh-trust-labs/opencred-vc-schemas/ed460795866ce51aebf92e9fccc5f30ff0482dcb/schemas/business-entity/v1/schema.json","upstreamOwner":"OpenCred","upstreamLicense":"MIT"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "open-badges/v3",
    schema: openBadgesV3,
    contextUrl: "https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.3.json",
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "fb2d04ab56e8465fa3d41198272fa05c9038de5b99a6e0d870dec9f9aa21b75f",
    source: {"kind":"referenced","upstreamUrl":"https://purl.imsglobal.org/spec/ob/v3p0/schema/json/ob_v3p0_achievementcredential_schema.json","upstreamOwner":"1EdTech Consortium","upstreamLicense":"1EdTech Specification License (royalty-free)"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "dif/verified-person/v1",
    schema: difVerifiedPersonV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "a4c06ed2eb7267baaed9f72c7ed76eb0ddae497869ec6fadb85911c1d7412bd3",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/decentralized-identity/credential-schemas/main/dif-recommended-schemas/verified-person-schema/v1.0/VerifiedPerson.schema.json","upstreamOwner":"Decentralized Identity Foundation (DIF)","upstreamLicense":"Apache-2.0"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "dif/proof-of-age/v1",
    schema: difProofOfAgeV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "c13b5d519fad8c74e0af1a97fbda147f234e81bfc116a25897d62049537f2c0f",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/decentralized-identity/credential-schemas/main/dif-recommended-schemas/proof-of-age-schema/v1.0/ProofOfAge.schema.json","upstreamOwner":"Decentralized Identity Foundation (DIF)","upstreamLicense":"Apache-2.0"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/commercial-invoice/v1",
    schema: traceabilityCommercialInvoiceV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "5f8cef713de121898e78f1602a89def134d18d88771e97907d80d91926bc9f6a",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/CommercialInvoiceCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/bill-of-lading/v1",
    schema: traceabilityBillOfLadingV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "0a94f25887606ae9339ec43c9b699fa612e0f9205e11d68e808fb45f59428757",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/BillOfLadingCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/house-bill-of-lading/v1",
    schema: traceabilityHouseBillOfLadingV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "62ff1357857847df16f1cd8fbd97a8723d2021098139a46e2ddb8b4926afbcfe",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/HouseBillOfLadingCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/usmca-certification-of-origin/v1",
    schema: traceabilityUsmcaCertificationOfOriginV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "51ed4eae077f59706fe9db25ad59f502a035e22998a5eb7c5a2269262ee3ff72",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/USMCACertificationOfOrigin.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/certification-of-origin/v1",
    schema: traceabilityCertificationOfOriginV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "c02225544c084a594b648f9237d6768d824cb22191fa59b975e5ba68ab32cc91",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/CertificationOfOrigin.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/purchase-order/v1",
    schema: traceabilityPurchaseOrderV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "453f0ba77f2df685725123263c976c9d4486c9f61d1b9c048306baea044c20fd",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/PurchaseOrderCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/order-confirmation/v1",
    schema: traceabilityOrderConfirmationV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "d6bc31a22ec389cdce44389e514054e9d11f7d49e402eb5a0eed64ba89a46b0c",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/OrderConfirmationCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/packing-list/v1",
    schema: traceabilityPackingListV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "d757e89b7244dfc182f5f810fbaa4c1a23111bf8a96e2d872e48f1b17c38a375",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/PackingListCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/iata-air-waybill/v1",
    schema: traceabilityIataAirWaybillV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "6dd12e20617b59298ff7e8730e39c2b504af01de802c0572943478f5cb3efc6c",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/IATAAirWaybillCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/importer-security-filing/v1",
    schema: traceabilityImporterSecurityFilingV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "5e0456e5ef20e64494cdefbb61ad64dae3507ee3cc477c2bc4ee70b254ad5409",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/ImporterSecurityFilingCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/mill-test-report/v1",
    schema: traceabilityMillTestReportV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "bc871be927bcd682da3bbdf49b9ded44ef43711c7f3ac225da559e1f6c64bec4",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/MillTestReportCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/sbom/v1",
    schema: traceabilitySbomV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "33045545d41885174e777170a13adb992821abec824ed1ef5a62dca255994afb",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/SoftwareBillofMaterialsCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/gap-inspection/v1",
    schema: traceabilityGapInspectionV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "2dca37b0c726ee3d48b17ed5bd58f6a7f3e3a8314bf536a29ef31ddbaf88bb0d",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/GAPInspectionCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/food-grade-inspection/v1",
    schema: traceabilityFoodGradeInspectionV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "444e258954890e41b922ea706f1d9e0f6b73e26d984114741c1f7525f0cfa4a1",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/FoodGradeInspectionCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/phytosanitary/v1",
    schema: traceabilityPhytosanitaryV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "ee1805e2610097fb350f62ba4ed8d78cfe64defc8309ec1a2365e41e060f4d07",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/PhytosanitaryCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/oil-and-gas-product/v1",
    schema: traceabilityOilAndGasProductV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "cc6202923307e029b336e60ef269c6c923571e2b8bb484bdf192f430a7e41f5e",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/OilAndGasProductCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/natural-gas-environmental-passport/v1",
    schema: traceabilityNaturalGasEnvironmentalPassportV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "47eb2a0bd02000cb61e933a9e908ddd815272e04aae2dfffb4ed8f2b383cb372",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/NaturalGasProducerEnvironmentalPassportCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/sima-steel-import-license/v1",
    schema: traceabilitySimaSteelImportLicenseV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "f65595a1868a49e84a86a722a93095fd1524ae968e8f4599e75a55496b69e6a0",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/SIMASteelImportLicenseCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/shipping-instructions/v1",
    schema: traceabilityShippingInstructionsV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "b00196b29e04567ed530d3bb2a42a7440c6ca4cf773bf1e9a4841bab501ea013",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/ShippingInstructionsCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/freight-manifest/v1",
    schema: traceabilityFreightManifestV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "362e03490fa5108975be41d6c34c0d60adbc3c3457fc071a8aafb3cb53e7ca40",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/FreightManifestCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  registry.register({
    id: "traceability/delivery-schedule/v1",
    schema: traceabilityDeliveryScheduleV1,
    version: "1.0.0",
    lastUpdated: "2026-04-08T00:00:00Z",
    checksum: "3238a5479e2acdb94e02fb039f10b7cb33be0d7435ac7e79261ee54f12c790ee",
    source: {"kind":"referenced","upstreamUrl":"https://raw.githubusercontent.com/w3c-ccg/traceability-vocab/main/docs/openapi/components/schemas/credentials/DeliveryScheduleCredential.yml","upstreamOwner":"W3C CCG Traceability Vocabulary","upstreamLicense":"W3C-20150513"},
  } satisfies SchemaDefinition);
  return registry;
}
